config/routes.rb
Rails.application.routes.draw do
  root 'trees#index'
  resources :trees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tree.rb
class Tree < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :set_tree, only: [:show, :edit, :update, :destroy]

  # GET /trees
  # GET /trees.json
  def index
    @trees = Tree.all
  end

  # GET /trees/1
  # GET /trees/1.json
  def show
  end

  # GET /trees/new
  def new
    @tree = Tree.new
  end

  # GET /trees/1/edit
  def edit
  end

  # POST /trees
  # POST /trees.json
  def create
    @tree = Tree.new(tree_params)

    respond_to do |format|
      if @tree.save
        format.html { redirect_to @tree, notice: 'Tree was successfully created.' }
        format.json { render :show, status: :created, location: @tree }
      else
        format.html { render :new }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trees/1
  # PATCH/PUT /trees/1.json
  def update
    respond_to do |format|
      if @tree.update(tree_params)
        format.html { redirect_to @tree, notice: 'Tree was successfully updated.' }
        format.json { render :show, status: :ok, location: @tree }
      else
        format.html { render :edit }
        format.json { render json: @tree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trees/1
  # DELETE /trees/1.json
  def destroy
    @tree.destroy
    respond_to do |format|
      format.html { redirect_to trees_url, notice: 'Tree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tree
      @tree = Tree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tree_params
      params.require(:tree).permit(:wood, :leaftype, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyFirstCrapplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/trees/_form.html.erb
<%= form_with(model: tree, local: true) do |form| %>
  <% if tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wood %>
    <%= form.text_field :wood %>
  </div>

  <div class="field">
    <%= form.label :leaftype %>
    <%= form.text_field :leaftype %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trees</h1>

<table>
  <thead>
    <tr>
      <th>Wood</th>
      <th>Leaftype</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trees.each do |tree| %>
      <tr>
        <td><%= tree.wood %></td>
        <td><%= tree.leaftype %></td>
        <td><%= tree.age %></td>
        <td><%= link_to 'Show', tree %></td>
        <td><%= link_to 'Edit', edit_tree_path(tree) %></td>
        <td><%= link_to 'Destroy', tree, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tree', new_tree_path %>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form', tree: @tree %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wood:</strong>
  <%= @tree.wood %>
</p>

<p>
  <strong>Leaftype:</strong>
  <%= @tree.leaftype %>
</p>

<p>
  <strong>Age:</strong>
  <%= @tree.age %>
</p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>